server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript text/html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache CSS e JS per 1 giorno
    location ~* \.(css|js)$ {
        expires 1d;
        add_header Cache-Control "public, max-age=86400";
    }
}
